name: CI

# 定义触发工作流的事件
on:
  push:
    branches:
      - master # 当master分支有推送时触发

  pull_request:
    branches:
      - master # 当向master分支发起拉取请求时触发

jobs:
  lint:
    runs-on: ubuntu-latest # 指定运行任务的环境，这里是最新的Ubuntu
    steps:
      - name: Checkout code # 检出代码步骤
        uses: actions/checkout@v4 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        node_version: [22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build
