name: PR

# 定义触发工作流的事件
on:
  pull_request:
    branches:
      - master # 当向master分支发起拉取请求时触发

jobs:
  lint:
    runs-on: ubuntu-latest # 指定运行任务的环境，这里是最新的Ubuntu
    steps:
      - name: Checkout code # 检出代码步骤
        uses: actions/checkout@v4 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm run lint
